### PR TITLE
Add initial benchmark.

### PR DESCRIPTION
**Pull request by jdalton**
This is just a couple basic benchmarks but should be enough to get the ball rolling.

<table>
<tr>
<th></th><th>size</th><th>acorn</th><th>esmod</th>
</tr>
<tr>
<td>react</td><td>804 kB</td><td>50ms</td><td>15ms</td>
</tr>
<tr>
<td>angry bots</td><td>19.4 MB</td><td>8.9s</td><td>1.4s</td>
</tr>
</table>

### CODE REVIEW

**Comment by jdalton** [comment]
btw I tried parsing AngryBots.js (not in this PR) which is 19MB and it takes ~1.4s.

**Comment by RReverser** [comment]
Could you add regular Acorn to the suite? Would be nice to have what to compare numbers with.

**Comment by RReverser** [comment]
And from DM

> How safe is to use ES6 code in benchmark? I mean, I'd like to be sure we don't have overhead of unoptimized syntactic constructs anywhere (so that numbers are stable).

**Comment by jdalton** [comment]
> Could you add regular Acorn to the suite? Would be nice to have what to compare numbers with.

Done.

> How safe is to use ES6 code in benchmark? I mean, I'd like to be sure we don't have overhead of unoptimized syntactic constructs anywhere (so that numbers are stable).

It's fine for the wrapper.
There's no difference in results using an arrow or traditional function to hold the test case.

**Comment by jdalton** [comment]
> Could you add regular Acorn to the suite? Would be nice to have what to compare numbers with.

Done.

**Comment by jdalton** [comment]
<table>
<tr>
<th></th><th>size</th><th>acorn</th><th>esmod</th>
</tr>
<tr>
<td>react</td><td>804 kB</td><td>50ms</td><td>15ms</td>
</tr>
<tr>
<td>angry bots</td><td>19 MB</td><td>8.9s</td><td>1.4s</td>
</tr>
</table>

**Comment by jdalton** [comment]
🤘 What other ideas do you have to improve perf?

**Comment by RReverser** [comment]
I have few for the parser, but some bigger wins might apply only to the full transformation cycle (`transform`) - but again, need benchmarks first to prove them.

**Comment by RReverser** [comment]
I'll play with parser ones though when I get some time.

**Comment by RReverser** [comment]
React example looks somewhat specific though in terms that there is only one top-level statement (IIFE), this is why on jsPerf I added at least one real-world example with `import`, `export` and some top-level content - otherwise it's too easy to speed up benchmark but it won't reflect real-world samples :)

**Comment by RReverser** [comment]
At the very least, could strip IIFE wrapper from React example.

**Comment by jdalton** [comment]
Totally! This PR wasn't the end-of-the-line for benchmarks. It was the foundation for more 😃

**Comment by RReverser** [comment]
@jdalton Sure, just explaining why these examples might be not representative (I didn't see angry bots one though).

**Comment by jdalton** [comment]
Ya, that one is 19.4 MB so I want to avoid including that in the repo.
I may add it tonight, to pull it down using [got](https://www.npmjs.com/package/got) and run, though.

**Comment by RReverser** [comment]
Wondering if Github's LFS would help with it.

**Comment by RReverser** [comment]
Hmm, just realized that *-bench files have quite a bit of duplicative code. Makes it slightly less scalable in terms of adding fixtures (ideally each fixture would be a separate Suite where different *-bench get same content and compete with each other).

**Comment by jdalton** [comment]
Cool, but be careful not to get hung up on superfluous stuff. Could spend 3 hours streamlining benchmarks or optimizing the parser. I think the dup code (like 8 lines) is OK for now.

**Comment by RReverser** [comment]
@jdalton Well, it is important stuff - when performance is the center of the project, benchmarks should be easily extendable to measure things (as they drive all the other changes).

**Comment by RReverser** [comment]
Anyway, I'll change that myself, np.

**Comment by RReverser** [comment]
Done; also added ES6 module fixture which in turn helped to reveal that acorn parser didn't use `sourceType: "module"`. Also looks like `async` was adding some overhead (given that we perform only synchronous processing in benchmark), removing it cut down numbers locally by ~10%.

Current numbers:

```
fixture/react@15.4.2.js (804 kB):
  ./acorn-parse-bench.js in 58ms; 17.36 ops/sec ±5.38% (33 runs sampled)
  ./esmod-parse-bench.js in 18ms; 58.62 ops/sec ±9.51% (63 runs sampled)
fixture/rollup.es.js (311 kB):
  ./acorn-parse-bench.js in 40ms; 25.42 ops/sec ±4.14% (46 runs sampled)
  ./esmod-parse-bench.js in 15ms; 69.00 ops/sec ±1.91% (67 runs sampled)
```

**Comment by RReverser** [comment]
`rollup.es.js` is also quite a good extra test - looks like `transform` indeed doesn't break it and changes only ES6 imports.

**Comment by jdalton** [comment]
>rollup.es.js is also quite a good extra test - looks like transform indeed doesn't break it and changes only ES6 imports.

Awesome!!!

> also added ES6 module fixture which in turn helped to reveal that acorn parser didn't use sourceType: "module".

The acorn test did have `sourceType: "module"` specified.
https://github.com/RReverser/esmod/commit/bf280ad2f1e62c6c20b5f3e2fcabbd8f12846a1f#diff-fb1d15c3b9bc6149f51fd6a949b0a9adR11

>  removing it cut down numbers locally by ~10%
>  ./acorn-parse-bench.js in 58ms; 17.36 ops/sec ±5.38% (33 runs sampled)
  ./esmod-parse-bench.js in 18ms; 58.62 ops/sec ±9.51% (63 runs sampled)

Those are roughly the same numbers [I was seeing](https://github.com/RReverser/esmod/pull/1#issue-214290225). You're probably just seeing noise between retests. The "async" option doesn't affect the test loop (there is no difference). It just gives a pause between samples to let things like UI update instead of hammering the CPU.

**Comment by jdalton** [comment]
>  ./acorn-parse-bench.js in 58ms; 17.36 ops/sec ±5.38% (33 runs sampled)
  ./esmod-parse-bench.js in 18ms; 58.62 ops/sec ±9.51% (63 runs sampled)

Those are roughly the same numbers I was seeing. The "async" option doesn't affect the test loop. It gives a pause between samples to let things like UI update instead of just hammering the CPU.

**Comment by RReverser** [comment]
> The acorn test did have sourceType: "module" specified.

Oh, my bad.

**Comment by jdalton** [comment]
Pretty rad stuff! So exciting 🎉

**Comment by RReverser** [comment]
For now my extra trick don't seem to improve performance any significantly. Maybe engines are smart enough and optimize what we have well (and it's indeed already quite fast).

Perhaps time to get it fully working, and then will make sense to try again.

**Pull request merged**
